title: Hanni Studios
description: Vintage and handmade finds

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Vintage Finds"
    url: "/vintage/"
  - title: "DIY"
    url: "/diy/"
  - title: "Blog"
    url: "/blog/"

